name: Create GH Release

on:
#  push:
#    branches:
#      - master
  pull_request:
    branches:
      - master

jobs:
  create_release:
    name: Create GH release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        -
      - name: Get current version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Create GH release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version }}
          release_name: ${{ steps.package-version.outputs.current-version }}
          draft: false
          prerelease: false
          body: |
            Version ${{ steps.package-version.outputs.current-version }} is now available.

